---
title: "Measuring public service motivation"
date: "2017-10-31"
---

**Abstract**: Public service motivation (PSM) has now become an established field of inquiry in public administration research. With the growth of this literature, researchers have created several quantitative indexes that measure PSM. However, we are still not sure how internally and externally valid these scales are. Do these different indexes capture the same dimensions and types of PSM? In this paper, we collect a unique dataset that measures four different PSM indexes (Perry, Grant, International, and MSPB5) simultaneously in a single sample. With this data, we use visual and statistical methods to compare the equality of distributions for these four PSM indexes. We then use our data to replicate research connecting PSM and personality traits to test the external validity of these different measures. Our findings have important implications for future PSM-focused research and can potentially lead to a more unified, standardized, and valid PSM index.
